
// --------------trainer------------
export const FETCH_STORIES_START = 'FETCH_STORIES_START'
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS'
export const FETCH_STORIES_ERROR = 'FETCH_STORIES_ERROR'

export const FETCH_STORY_BY_ID_START  = 'FETCH_STORY_BY_ID_START'
export const FETCH_STORY_BY_ID_SUCCESS = 'FETCH_STORY_BY_ID_SUCCESS'
export const FETCH_STORY_BY_ID_ERROR = 'FETCH_STORY_BY_ID_ERROR'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'

export const CREATE_STORY = 'CREATE_STORY'
export const RESET_STORY_CREATION = 'RESET_STORY_CREATION'

// --------------lesson and topics------------
export const FETCH_LESSON_TOPICS_START = 'FETCH_LESSON_TOPICS_START'
export const FETCH_LESSON_TOPICS_SUCCESS = 'FETCH_LESSON_TOPICS_SUCCESS'
export const FETCH_LESSON_TOPICS_ERROR = 'FETCH_LESSON_TOPICS_ERROR'

export const FETCH_LESSON_TOPICS_BY_ID_START  = 'FETCH_LESSON_TOPICS_BY_ID_START'
export const FETCH_LESSON_TOPICS_BY_ID_SUCCESS = 'FETCH_LESSON_TOPICS_BY_ID_SUCCESS'
export const FETCH_LESSON_TOPICS_BY_ID_ERROR = 'FETCH_LESSON_TOPICS_BY_ID_ERROR'

// export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'

// export const CREATE_STORY = 'CREATE_STORY'
// export const RESET_STORY_CREATION = 'RESET_STORY_CREATION'


// --------------group and member------------
export const FETCH_GROUP_MEMBER_START = 'FETCH_GROUP_MEMBER_START'
export const FETCH_GROUP_MEMBER_SUCCESS = 'FETCH_GROUP_MEMBER_SUCCESS'
export const FETCH_GROUP_MEMBER_ERROR = 'FETCH_GROUP_MEMBER_ERROR'

export const FETCH_GROUP_MEMBER_BY_ID_START  = 'FETCH_GROUP_MEMBER_BY_ID_START'
export const FETCH_GROUP_MEMBER_BY_ID_SUCCESS = 'FETCH_GROUP_MEMBER_BY_ID_SUCCESS'
export const FETCH_GROUP_MEMBER_BY_ID_ERROR = 'FETCH_GROUP_MEMBER_BY_ID_ERROR'

// export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'

// export const CREATE_STORY = 'CREATE_STORY'
// export const RESET_STORY_CREATION = 'RESET_STORY_CREATION'