export const FETCH_STORIES_START = 'FETCH_STORIES_START'
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS'
export const FETCH_STORIES_ERROR = 'FETCH_STORIES_ERROR'

export const FETCH_STORY_BY_ID_START  = 'FETCH_STORY_BY_ID_START'
export const FETCH_STORY_BY_ID_SUCCESS = 'FETCH_STORY_BY_ID_SUCCESS'
export const FETCH_STORY_BY_ID_ERROR = 'FETCH_STORY_BY_ID_ERROR'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION'
